# Generated by Django 2.2.5 on 2022-04-12 21:40

from django.db import migrations, models
import django.db.models.deletion
import identify.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_images', models.ImageField(upload_to='upload_images')),
                ('nation1', models.CharField(blank=True, max_length=20, null=True)),
                ('nation2', models.CharField(blank=True, max_length=20, null=True)),
                ('nation3', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_nation', models.CharField(blank=True, max_length=20, null=True)),
                ('time_consuming', models.CharField(blank=True, max_length=50, null=True)),
                ('user_assess', models.CharField(blank=True, default='未填写', max_length=50, null=True)),
                ('user_update', models.CharField(blank=True, default='未修改', max_length=50, null=True)),
                ('user_change', models.CharField(blank=True, default='否', max_length=20, null=True)),
                ('user_propose', models.TextField(blank=True, default='未填写', max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '识别结果',
                'verbose_name_plural': '识别结果',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='MergedImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_1_head_image', models.ImageField(blank=True, default=None, null=True, upload_to=identify.models._merge_image_person_1_head_image_path, verbose_name='第一个人的头像图片')),
                ('person_2_head_image', models.ImageField(blank=True, default=None, null=True, upload_to=identify.models._merge_image_person_2_head_image_path, verbose_name='第二个人的头像图片')),
                ('background_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='背景名称')),
                ('result_image', models.ImageField(blank=True, default=None, null=True, upload_to=identify.models._merge_image_person_merged_path, verbose_name='合成后的图片')),
                ('person_1_identification', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_1_merged_images', to='identify.ImagesPost', verbose_name='第一个人的识别结果')),
                ('person_2_identification', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_2_merged_images', to='identify.ImagesPost', verbose_name='第二个人的识别结果')),
            ],
            options={
                'verbose_name': '图像合成',
                'verbose_name_plural': '图像合成',
            },
        ),
    ]
